/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Michele (https://sketchfab.com/michelerispoli2009)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/macbook-4443e59ec55242a889e710bc0632879e
title: MacBook
*/

import React, { useEffect, useLayoutEffect, useRef, useState } from "react";
import { Html, Mask, useGLTF, useMask } from "@react-three/drei";
import Site from "./Site";

export function Mac2(props) {
  const { nodes, materials } = useGLTF("./models/macbook.glb");
  const stencil = useMask(1, true)
  useEffect(() => {
    Object.values(nodes).forEach(
      (node) =>
        node.material &&
        Object.assign(node.material, stencil),
    )
  }, [])
  const [video] = useState(() => Object.assign(document.createElement('video'), { src: './Desktop 2021.07.22 - 12.52.58.02_Trim.mp4', crossOrigin: 'Anonymous', loop: true, muted: true }))
  useEffect(() => void video.play(), [video])
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[2.1, 0.25, 0.18]}
            rotation={[-Math.PI, -0.49, -Math.PI]}
            scale={[1, 0.15, 1]}
          >
            <mesh
              geometry={nodes.Object_4.geometry}
              material={materials.Materiale}
            />
          </group>
          <group
            position={[17.17, 0.05, 1.26]}
            rotation={[-Math.PI, -0.49, -Math.PI]}
            scale={[1, 0.24, 1]}
          >
            <mesh
              geometry={nodes.Object_6.geometry}
              material={materials["Materiale.005"]}
            />
            
          </group>
          <group
            position={[-5.58, 0.05, 13.29]}
            rotation={[-Math.PI, -0.49, -Math.PI]}
            scale={[1, 0.24, 1]}
          >
            <mesh
              geometry={nodes.Object_8.geometry}
              material={materials["Materiale.005"]}
            />
          </group>
          <group
            position={[-13.05, 0.05, -0.84]}
            rotation={[-Math.PI, -0.49, -Math.PI]}
            scale={[1, 0.24, 1]}
          >
            <mesh
              geometry={nodes.Object_10.geometry}
              material={materials["Materiale.005"]}
            />
          </group>
          <group
            position={[-3.96, 10.18, -11.27]}
            rotation={[-1.84, -0.14, -2.67]}
            scale={[1, 0.15, 1]}
          >
            <mesh
              geometry={nodes.Object_12.geometry}
              material={materials.Materiale}
            />
          </group>
          <group
            position={[-3.92, 10, -11.19]}
            rotation={[-1.84, -0.14, -2.67]}
            scale={[0.95, 0.04, 0.95]}
          >
            
            <mesh
              geometry={nodes.Object_14.geometry}
              material={materials["Materiale.001"]}
            />
          </group>
          <group
            position={[9.36, 0.59, -13.04]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_16.geometry}
              material={materials["Materiale.002"]}
            />
          </group>
          <group
            position={[10.14, 0.57, -11.57]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_18.geometry}
              material={materials["Materiale.002"]}
            />
          </group>
          <group
            position={[13.27, 0.5, -5.64]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_20.geometry}
              material={materials["Materiale.002"]}
            />
          </group>
          <group
            position={[11.79, 0.5, -4.86]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_22.geometry}
              material={materials["Materiale.002"]}
            />
          </group>
          <group
            position={[8.66, 0.57, -10.78]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_24.geometry}
              material={materials["Materiale.002"]}
            />
          </group>
          <group
            position={[7.88, 0.59, -12.26]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_26.geometry}
              material={materials["Materiale.002"]}
            />
          </group>
          <group
            position={[6.41, 0.59, -11.48]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_28.geometry}
              material={materials["Materiale.002"]}
            />
          </group>
          <group
            position={[7.19, 0.57, -10]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_30.geometry}
              material={materials["Materiale.002"]}
            />
          </group>
          <group
            position={[10.32, 0.5, -4.08]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_32.geometry}
              material={materials["Materiale.002"]}
            />
          </group>
          <group
            position={[7.37, 0.5, -2.52]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_34.geometry}
              material={materials["Materiale.002"]}
            />
          </group>
          <group
            position={[4.24, 0.57, -8.44]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_36.geometry}
              material={materials["Materiale.002"]}
            />
          </group>
          <group
            position={[3.46, 0.59, -9.92]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_38.geometry}
              material={materials["Materiale.002"]}
            />
          </group>
          <group
            position={[4.92, 0.59, -10.69]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_40.geometry}
              material={materials["Materiale.002"]}
            />
          </group>
          <group
            position={[5.71, 0.57, -9.22]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_42.geometry}
              material={materials["Materiale.002"]}
            />
          </group>
          <group
            position={[8.84, 0.5, -3.3]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_44.geometry}
              material={materials["Materiale.002"]}
            />
          </group>
          <group
            position={[2.75, 0.57, -7.66]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_46.geometry}
              material={materials["Materiale.002"]}
            />
          </group>
          <group
            position={[1.97, 0.59, -9.13]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_48.geometry}
              material={materials["Materiale.002"]}
            />
          </group>
          <group
            position={[0.5, 0.59, -8.36]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_50.geometry}
              material={materials["Materiale.002"]}
            />
          </group>
          <group
            position={[1.29, 0.57, -6.88]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_52.geometry}
              material={materials["Materiale.002"]}
            />
          </group>
          <group
            position={[-4.44, 0.5, 3.73]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_54.geometry}
              material={materials["Materiale.002"]}
            />
          </group>
          <group
            position={[-7.57, 0.57, -2.19]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_56.geometry}
              material={materials["Materiale.002"]}
            />
          </group>
          <group
            position={[-8.35, 0.59, -3.67]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_58.geometry}
              material={materials["Materiale.002"]}
            />
          </group>
          <group
            position={[-6.89, 0.59, -4.45]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_60.geometry}
              material={materials["Materiale.002"]}
            />
          </group>
          <group
            position={[-6.1, 0.57, -2.97]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_62.geometry}
              material={materials["Materiale.002"]}
            />
          </group>
          <group
            position={[-2.97, 0.5, 2.95]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_64.geometry}
              material={materials["Materiale.002"]}
            />
          </group>
          <group
            position={[-3.15, 0.57, -4.53]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_66.geometry}
              material={materials["Materiale.002"]}
            />
          </group>
          <group
            position={[-3.93, 0.59, -6.01]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_68.geometry}
              material={materials["Materiale.002"]}
            />
          </group>
          <group
            position={[-5.4, 0.59, -5.23]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_70.geometry}
              material={materials["Materiale.002"]}
            />
          </group>
          <group
            position={[-4.62, 0.57, -3.76]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_72.geometry}
              material={materials["Materiale.002"]}
            />
          </group>
          <group
            position={[-1.67, 0.57, -5.32]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_74.geometry}
              material={materials["Materiale.002"]}
            />
          </group>
          <group
            position={[-2.45, 0.59, -6.79]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_76.geometry}
              material={materials["Materiale.002"]}
            />
          </group>
          <group
            position={[-0.98, 0.59, -7.57]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_78.geometry}
              material={materials["Materiale.002"]}
            />
          </group>
          <group
            position={[-0.2, 0.57, -6.09]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_80.geometry}
              material={materials["Materiale.002"]}
            />
          </group>
          <group
            position={[-7.43, 0.5, 5.31]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_82.geometry}
              material={materials["Materiale.002"]}
            />
          </group>
          <group
            position={[-10.56, 0.57, -0.61]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_84.geometry}
              material={materials["Materiale.002"]}
            />
          </group>
          <group
            position={[-11.34, 0.59, -2.09]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_86.geometry}
              material={materials["Materiale.002"]}
            />
          </group>
          <group
            position={[-9.87, 0.59, -2.87]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_88.geometry}
              material={materials["Materiale.002"]}
            />
          </group>
          <group
            position={[-9.09, 0.57, -1.39]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_90.geometry}
              material={materials["Materiale.002"]}
            />
          </group>
          <group
            position={[-5.96, 0.5, 4.53]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_92.geometry}
              material={materials["Materiale.002"]}
            />
          </group>
          <group
            position={[-8.91, 0.5, 6.09]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_94.geometry}
              material={materials["Materiale.002"]}
            />
          </group>
          <group
            position={[-12.04, 0.57, 0.17]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_96.geometry}
              material={materials["Materiale.002"]}
            />
          </group>
          <group
            position={[-12.82, 0.59, -1.3]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_98.geometry}
              material={materials["Materiale.002"]}
            />
          </group>
          <group
            position={[9.72, 0.05, -12.82]}
            rotation={[-Math.PI, -0.49, -Math.PI]}
            scale={[1, 0.24, 1]}
          >
            <mesh
              geometry={nodes.Object_100.geometry}
              material={materials["Materiale.005"]}
            />
          </group>
          <group
            position={[2.19, 0.5, 0.22]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_102.geometry}
              material={materials["Materiale.002"]}
            />
          </group>
          <group
            position={[-11.26, 0.55, 1.64]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_104.geometry}
              material={materials["Materiale.003"]}
            />
          </group>
          <group
            position={[-8.31, 0.55, 0.08]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_106.geometry}
              material={materials["Materiale.003"]}
            />
          </group>
          <group
            position={[-9.78, 0.55, 0.86]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_108.geometry}
              material={materials["Materiale.003"]}
            />
          </group>
          <group
            position={[0.58, 0.55, -4.62]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_110.geometry}
              material={materials["Materiale.003"]}
            />
          </group>
          <group
            position={[-0.89, 0.55, -3.84]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_112.geometry}
              material={materials["Materiale.003"]}
            />
          </group>
          <group
            position={[-3.84, 0.55, -2.28]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_114.geometry}
              material={materials["Materiale.003"]}
            />
          </group>
          <group
            position={[-2.37, 0.55, -3.06]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_116.geometry}
              material={materials["Materiale.003"]}
            />
          </group>
          <group
            position={[-5.32, 0.55, -1.5]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_118.geometry}
              material={materials["Materiale.003"]}
            />
          </group>
          <group
            position={[-6.79, 0.55, -0.72]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_120.geometry}
              material={materials["Materiale.003"]}
            />
          </group>
          <group
            position={[2.06, 0.55, -5.41]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_122.geometry}
              material={materials["Materiale.003"]}
            />
          </group>
          <group
            position={[3.53, 0.55, -6.18]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_124.geometry}
              material={materials["Materiale.003"]}
            />
          </group>
          <group
            position={[6.49, 0.55, -7.74]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_126.geometry}
              material={materials["Materiale.003"]}
            />
          </group>
          <group
            position={[5.02, 0.55, -6.97]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_128.geometry}
              material={materials["Materiale.003"]}
            />
          </group>
          <group
            position={[7.97, 0.55, -8.53]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_130.geometry}
              material={materials["Materiale.003"]}
            />
          </group>
          <group
            position={[9.44, 0.55, -9.31]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_132.geometry}
              material={materials["Materiale.003"]}
            />
          </group>
          <group
            position={[10.92, 0.55, -10.09]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_134.geometry}
              material={materials["Materiale.003"]}
            />
          </group>
          <group
            position={[11.7, 0.54, -8.62]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_136.geometry}
              material={materials["Materiale.004"]}
            />
          </group>
          <group
            position={[10.22, 0.54, -7.83]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_138.geometry}
              material={materials["Materiale.004"]}
            />
          </group>
          <group
            position={[8.75, 0.54, -7.06]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_140.geometry}
              material={materials["Materiale.004"]}
            />
          </group>
          <group
            position={[5.8, 0.54, -5.5]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_142.geometry}
              material={materials["Materiale.004"]}
            />
          </group>
          <group
            position={[7.26, 0.54, -6.27]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_144.geometry}
              material={materials["Materiale.004"]}
            />
          </group>
          <group
            position={[4.31, 0.54, -4.71]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_146.geometry}
              material={materials["Materiale.004"]}
            />
          </group>
          <group
            position={[2.84, 0.54, -3.93]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_148.geometry}
              material={materials["Materiale.004"]}
            />
          </group>
          <group
            position={[-6.01, 0.54, 0.75]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_150.geometry}
              material={materials["Materiale.004"]}
            />
          </group>
          <group
            position={[-4.55, 0.54, -0.02]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_152.geometry}
              material={materials["Materiale.004"]}
            />
          </group>
          <group
            position={[-1.59, 0.54, -1.59]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_154.geometry}
              material={materials["Materiale.004"]}
            />
          </group>
          <group
            position={[-3.06, 0.54, -0.81]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_156.geometry}
              material={materials["Materiale.004"]}
            />
          </group>
          <group
            position={[-0.11, 0.54, -2.37]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_158.geometry}
              material={materials["Materiale.004"]}
            />
          </group>
          <group
            position={[1.36, 0.54, -3.15]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_160.geometry}
              material={materials["Materiale.004"]}
            />
          </group>
          <group
            position={[-9, 0.54, 2.33]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_162.geometry}
              material={materials["Materiale.004"]}
            />
          </group>
          <group
            position={[-7.53, 0.54, 1.56]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_164.geometry}
              material={materials["Materiale.004"]}
            />
          </group>
          <group
            position={[-10.48, 0.54, 3.12]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_166.geometry}
              material={materials["Materiale.004"]}
            />
          </group>
          <group
            position={[-9.69, 0.52, 4.62]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_168.geometry}
              material={materials["Materiale.005"]}
            />
          </group>
          <group
            position={[-6.74, 0.52, 3.05]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_170.geometry}
              material={materials["Materiale.005"]}
            />
          </group>
          <group
            position={[-8.21, 0.52, 3.83]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_172.geometry}
              material={materials["Materiale.005"]}
            />
          </group>
          <group
            position={[2.15, 0.52, -1.65]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_174.geometry}
              material={materials["Materiale.005"]}
            />
          </group>
          <group
            position={[0.68, 0.52, -0.87]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_176.geometry}
              material={materials["Materiale.005"]}
            />
          </group>
          <group
            position={[-2.27, 0.52, 0.69]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_178.geometry}
              material={materials["Materiale.005"]}
            />
          </group>
          <group
            position={[-0.8, 0.52, -0.09]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_180.geometry}
              material={materials["Materiale.005"]}
            />
          </group>
          <group
            position={[-3.75, 0.52, 1.47]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_182.geometry}
              material={materials["Materiale.005"]}
            />
          </group>
          <group
            position={[-5.22, 0.52, 2.25]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_184.geometry}
              material={materials["Materiale.005"]}
            />
          </group>
          <group
            position={[3.64, 0.52, -2.43]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_186.geometry}
              material={materials["Materiale.005"]}
            />
          </group>
          <group
            position={[5.1, 0.52, -3.21]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_188.geometry}
              material={materials["Materiale.005"]}
            />
          </group>
          <group
            position={[8.06, 0.52, -4.77]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_190.geometry}
              material={materials["Materiale.005"]}
            />
          </group>
          <group
            position={[6.59, 0.52, -4]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_192.geometry}
              material={materials["Materiale.005"]}
            />
          </group>
          <group
            position={[9.54, 0.52, -5.56]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_194.geometry}
              material={materials["Materiale.005"]}
            />
          </group>
          <group
            position={[11.01, 0.52, -6.34]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_196.geometry}
              material={materials["Materiale.005"]}
            />
          </group>
          <group
            position={[12.49, 0.52, -7.12]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_198.geometry}
              material={materials["Materiale.005"]}
            />
          </group>
          <group
            position={[-4.07, 10.17, -11.5]}
            rotation={[1.31, 0.14, 2.67]}
            scale={0.74}
          >
            <mesh
              geometry={nodes.Object_200.geometry}
              material={materials["Materiale.006"]}
            />
          </group>
          <group
            position={[8.93, 0.59, -13.85]}
            rotation={[-3.13, -0.49, -3.14]}
            scale={[0.28, 0.11, 0.28]}
          >
            <mesh
              geometry={nodes.Object_202.geometry}
              material={materials["Materiale.007"]}
            />
          </group>
          <group
            position={[-14.44, 0.29, -0.01]}
            rotation={[-Math.PI, -0.49, -Math.PI]}
            scale={[0.42, 0.05, 0.46]}
          >
            <mesh
              geometry={nodes.Object_204.geometry}
              material={materials["Materiale.004"]}
            />
          </group>
          <group
            position={[-3.94, 10.37, -11.24]}
            rotation={[1.3, 0.14, -0.47]}
            scale={[14.12, 2, 9.04]}
          >
              {/* <Mask id={1} colorWrite={true} depthWrite={false} geometry={nodes.Object_206.geometry}  >
               
               
               <Site distanceFactor={1.15} zIndexRange={[2, 0]}/>
          </Mask> */}
            {/* <mesh
              geometry={nodes.Object_206.geometry}
              position-y = {0.4}
              // material={materials["Materiale.009"]}
            /> */}
              {/* <meshBasicMaterial toneMapped={false} >
                <videoTexture attach='map' args={[video]} />
              </meshBasicMaterial> */}
              <Site rotation-x={-1.6} distanceFactor={1.15}  />
             
          </group>
          <group
            position={[-3.35, 1.13, -8.31]}
            rotation={[1.31, 0.13, -0.47]}
            scale={[0.46, 0.95, 0.46]}
          >
            <mesh
              geometry={nodes.Object_208.geometry}
              material={materials.Materiale}
            />
          </group>
        </group>
      </group>
    
    </group>
    
  );
}

useGLTF.preload("./models/macbook.glb");
